In [1]:
import os
import pandas
import pathlib
cwd = pathlib.Path.cwd()
import shutil
import re
import tensorflow as tf
import random
import numpy
import pandas as pd
import datetime
from matplotlib import pyplot as plt
from contextlib import redirect_stdout
from PIL import Image

width, height, depth = 64, 64, 1
seed = random.randint(1000000, 9000000)
batch_size = 1
image_dir = cwd / "Test_Data"

In [2]:
train_set = tf.keras.preprocessing.image_dataset_from_directory(str(image_dir), image_size = (width, height), seed = seed, subset = "training", validation_split = 0.2, batch_size = batch_size, label_mode = "categorical", color_mode = "grayscale")
valid_set = tf.keras.preprocessing.image_dataset_from_directory(str(image_dir), image_size = (width, height), seed = seed, subset = "validation", validation_split = 0.2, batch_size = batch_size, label_mode = "categorical", color_mode = "grayscale")

Found 48 files belonging to 2 classes.
Using 39 files for training.
Found 48 files belonging to 2 classes.
Using 9 files for validation.


In [3]:
image_batch, labels_batch = next(iter(train_set))
first_image = image_batch[0]

In [4]:
print(first_image)

tf.Tensor(
[[[  5.]
  [  5.]
  [ 12.]
  ...
  [  9.]
  [ 18.]
  [ 15.]]

 [[ 11.]
  [ 16.]
  [ 22.]
  ...
  [  8.]
  [ 17.]
  [ 18.]]

 [[  9.]
  [ 19.]
  [ 25.]
  ...
  [ 17.]
  [ 13.]
  [ 14.]]

 ...

 [[105.]
  [162.]
  [163.]
  ...
  [ 19.]
  [ 27.]
  [ 23.]]

 [[118.]
  [182.]
  [165.]
  ...
  [ 18.]
  [ 21.]
  [ 19.]]

 [[ 92.]
  [144.]
  [137.]
  ...
  [  9.]
  [ 15.]
  [ 13.]]], shape=(64, 64, 1), dtype=float32)


In [5]:
print(numpy.min(first_image), numpy.max(first_image))

0.0 255.0


In [6]:
print(tf.reduce_sum(first_image))

tf.Tensor(125712.0, shape=(), dtype=float32)


In [7]:
print(numpy.min(first_image) / tf.reduce_sum(first_image), numpy.max(first_image) / tf.reduce_sum(first_image))
print(type(numpy.min(first_image) / tf.reduce_sum(first_image)), type(numpy.max(first_image) / tf.reduce_sum(first_image)))
print(tf.reduce_sum(first_image / tf.reduce_sum(first_image)))

tf.Tensor(0.0, shape=(), dtype=float32) tf.Tensor(0.002028446, shape=(), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'> <class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(1.0, shape=(), dtype=float32)


In [10]:
def norm_field(tensor_image, something_else):
    '''
    '''
    tensor_image = tf.cast(tensor_image / tf.reduce_sum(tensor_image), tf.float32)
    # tensor_image = tensor_image / 255
    return tensor_image, something_else

In [11]:
normalized_ds = train_set.map(norm_field)

In [12]:
image_norms, _ = next(iter(normalized_ds))
first_norm = image_norms[0]

In [13]:
print(first_norm)

tf.Tensor(
[[[3.97734511e-05]
  [3.97734511e-05]
  [9.54562784e-05]
  ...
  [7.15922142e-05]
  [1.43184428e-04]
  [1.19320350e-04]]

 [[8.75015903e-05]
  [1.27275038e-04]
  [1.75003181e-04]
  ...
  [6.36375189e-05]
  [1.35229726e-04]
  [1.43184428e-04]]

 [[7.15922142e-05]
  [1.51139116e-04]
  [1.98867259e-04]
  ...
  [1.35229726e-04]
  [1.03410974e-04]
  [1.11365662e-04]]

 ...

 [[8.35242448e-04]
  [1.28865975e-03]
  [1.29661453e-03]
  ...
  [1.51139116e-04]
  [2.14776635e-04]
  [1.82957869e-04]]

 [[9.38653422e-04]
  [1.44775363e-03]
  [1.31252385e-03]
  ...
  [1.43184428e-04]
  [1.67048493e-04]
  [1.51139116e-04]]

 [[7.31831475e-04]
  [1.14547543e-03]
  [1.08979258e-03]
  ...
  [7.15922142e-05]
  [1.19320350e-04]
  [1.03410974e-04]]], shape=(64, 64, 1), dtype=float32)


In [14]:
print(numpy.min(first_norm), numpy.max(first_norm))
print(numpy.sum(first_norm))
# print(type(numpy.min(first_norm) / tf.reduce_sum(first_norm)), type(numpy.max(first_norm) / tf.reduce_sum(first_norm)))
# print(tf.reduce_sum(first_norm / tf.reduce_sum(first_norm)))

0.0 0.002028446
1.0
