In [1]:
import pandas as pd
import pathlib
cwd = pathlib.Path.cwd()
import random
import seqlogo
import numpy as np


In [5]:
# Setting seed for demonstration purposes
np.random.seed(42)

# Making some fake Position Frequency Data (PFM)
pfm = pd.DataFrame(np.random.randint(0, 36, size=(8, 4)))
# Convert to Position Weight Matrix (PWM)
pwm = seqlogo.pfm2pwm(pfm)
# print(pwm)
# print(pfm)
pfm

0   1   2   3
0  28  14   7  20
1  18  22  10  10
2  23  35  23   2
3  21   1  23  29
4   1  20  32  11
5  21  24  26  27
6  15  14   2   6
7  20   8  17   3

In [8]:
# Setting seed for demonstration purposes
np.random.seed(42)

# Making a fake PPM
random_ppm = np.random.dirichlet(np.ones(4), size=6)
ppm = seqlogo.Ppm(random_ppm)
print(random_ppm)
print(ppm)

[[0.08219683 0.52725178 0.2306407  0.15991069]
 [0.07037527 0.07036342 0.02482637 0.83443494]
 [0.16196168 0.21697225 0.00366528 0.61740079]
 [0.73563827 0.09828977 0.0826381  0.08343386]
 [0.17989796 0.368931   0.2804629  0.17070814]
 [0.49851022 0.07913752 0.18200371 0.24034854]]


A         C         G         T
0  0.082197  0.527252  0.230641  0.159911
1  0.070375  0.070363  0.024826  0.834435
2  0.161962  0.216972  0.003665  0.617401
3  0.735638  0.098290  0.082638  0.083434
4  0.179898  0.368931  0.280463  0.170708
5  0.498510  0.079138  0.182004  0.240349